library ImprovementExamEnrollmentFormConstant;

const examEnrollment = 'Inscrição em Melhoria';
const contacts = 'Contactos preferenciais';
const email = 'Endereço de email';
const phone = 'Contacto de telemóvel';
const enrollment = 'Inscrição no exame';
const exam = 'Exame de';
const examDate = 'Data do exame';
const approvalDeclaration = 'Declaro que obtive aprovação nesta unidade curricular no Ano Letivo';
const recognization = 'e tive conhecimento da classificação no dia';
const season = 'Pretende inscrição na época';
const declarations = 'Declarações';
const declarationsNote1 = 'Declaro que tomei conhecimento que, a inscrição no exame de melhoria está sujeita ao pagamento de emolumentos, conforme o previsto no ponto 6 da Tabela de Emolumentos da UP e Despacho n.º7/2016 do Diretor da Feup, a efetuar em acordo com os prazos acima definidos, não havendo direito ao seu reembolso. O não pagamento do emolumento, ainda que não realizado o exame respetivo, implicará a passagem do estudante à situação de devedor. Aos pedidos de inscrição em exames ou de regularização da inscrição em exames (obs.: quando um estudante se inscreve em exame mas não procede ao pagamento do respetivo emolumento dentro do prazo definido), fora de prazo, será aplicado o emolumento relativo à prática de atos fora de prazo previsto no ponto 9 da Tabela de Emolumentos da UP e Despacho n.º7/2016 do Diretor da FEUP.';
const declarationsNote2 = 'Declaro que tomei conhecimento que de acordo com o ponto 3 do Artigo 4.º - Consequências do não pagamento do regulamento de propinas da Universidade do Porto: 3 - Sempre que haja lugar a inscrição em exame ou em melhoria de classificação, tal não é permitido para os estudantes em incumprimento.';
const confirm = 'Confirmo';
const uc = 'unidade curricular';
const day = 'dia';
const month = 'mês';
const year = 'ano';
const schooolYear = 'ano letivo';
const examSeason = 'época de exames';
const fillAll = 'Por favor preencha todos os campos';